# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from moqentra.worker.v1 import worker_pb2 as moqentra_dot_worker_dot_v1_dot_worker__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in moqentra/worker/v1/worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerAgentServiceStub:
    """Bidirectional worker/agent stream.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenStream = channel.stream_stream(
                '/moqentra.worker.v1.WorkerAgentService/OpenStream',
                request_serializer=moqentra_dot_worker_dot_v1_dot_worker__pb2.WorkerAgentServiceOpenStreamRequest.SerializeToString,
                response_deserializer=moqentra_dot_worker_dot_v1_dot_worker__pb2.WorkerAgentServiceOpenStreamResponse.FromString,
                _registered_method=True)


class WorkerAgentServiceServicer:
    """Bidirectional worker/agent stream.
    """

    def OpenStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenStream': grpc.stream_stream_rpc_method_handler(
                    servicer.OpenStream,
                    request_deserializer=moqentra_dot_worker_dot_v1_dot_worker__pb2.WorkerAgentServiceOpenStreamRequest.FromString,
                    response_serializer=moqentra_dot_worker_dot_v1_dot_worker__pb2.WorkerAgentServiceOpenStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'moqentra.worker.v1.WorkerAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('moqentra.worker.v1.WorkerAgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerAgentService:
    """Bidirectional worker/agent stream.
    """

    @staticmethod
    def OpenStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/moqentra.worker.v1.WorkerAgentService/OpenStream',
            moqentra_dot_worker_dot_v1_dot_worker__pb2.WorkerAgentServiceOpenStreamRequest.SerializeToString,
            moqentra_dot_worker_dot_v1_dot_worker__pb2.WorkerAgentServiceOpenStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
