external:
  db: true
  s3: true
  oidc: true

networkPolicy:
  enabled: true

podDisruptionBudget:
  enabled: true
  minAvailable: 1

upgrade:
  hooks: true

resources:
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 1000m
    memory: 2Gi
