# coding: utf-8

"""
    Moqentra API

    Northbound HTTP API for Moqentra.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateUploadSessionRequest(BaseModel):
    """
    CreateUploadSessionRequest
    """ # noqa: E501
    resource_type: StrictStr
    resource_id: StrictStr
    version_id: StrictStr
    name: StrictStr
    media_type: StrictStr
    part_size: StrictInt
    total_size: StrictInt
    ttl_seconds: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["resource_type", "resource_id", "version_id", "name", "media_type", "part_size", "total_size", "ttl_seconds"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateUploadSessionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateUploadSessionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "resource_type": obj.get("resource_type"),
            "resource_id": obj.get("resource_id"),
            "version_id": obj.get("version_id"),
            "name": obj.get("name"),
            "media_type": obj.get("media_type"),
            "part_size": obj.get("part_size"),
            "total_size": obj.get("total_size"),
            "ttl_seconds": obj.get("ttl_seconds")
        })
        return _obj


