# coding: utf-8

"""
    Moqentra API

    Northbound HTTP API for Moqentra.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ImportJobResponse(BaseModel):
    """
    ImportJobResponse
    """ # noqa: E501
    id: StrictStr
    state: StrictStr
    source_url: StrictStr
    target_key: StrictStr
    media_type: StrictStr
    total_bytes: StrictInt
    transferred_bytes: StrictInt
    concurrency: StrictInt
    deadline_seconds: StrictInt
    digest: Optional[StrictStr] = None
    failure: Optional[StrictStr] = None
    retry_count: StrictInt
    __properties: ClassVar[List[str]] = ["id", "state", "source_url", "target_key", "media_type", "total_bytes", "transferred_bytes", "concurrency", "deadline_seconds", "digest", "failure", "retry_count"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ImportJobResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ImportJobResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "state": obj.get("state"),
            "source_url": obj.get("source_url"),
            "target_key": obj.get("target_key"),
            "media_type": obj.get("media_type"),
            "total_bytes": obj.get("total_bytes"),
            "transferred_bytes": obj.get("transferred_bytes"),
            "concurrency": obj.get("concurrency"),
            "deadline_seconds": obj.get("deadline_seconds"),
            "digest": obj.get("digest"),
            "failure": obj.get("failure"),
            "retry_count": obj.get("retry_count")
        })
        return _obj


