# coding: utf-8

"""
    Moqentra API

    Northbound HTTP API for Moqentra.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from moqentra_client.models.upload_part_info import UploadPartInfo
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UploadSessionResponse(BaseModel):
    """
    UploadSessionResponse
    """ # noqa: E501
    id: StrictStr
    target_key: StrictStr
    media_type: StrictStr
    part_size: StrictInt
    total_size: StrictInt
    parts: List[UploadPartInfo]
    state: StrictStr
    expires_at: StrictStr
    __properties: ClassVar[List[str]] = ["id", "target_key", "media_type", "part_size", "total_size", "parts", "state", "expires_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UploadSessionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in parts (list)
        _items = []
        if self.parts:
            for _item_parts in self.parts:
                if _item_parts:
                    _items.append(_item_parts.to_dict())
            _dict['parts'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UploadSessionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "target_key": obj.get("target_key"),
            "media_type": obj.get("media_type"),
            "part_size": obj.get("part_size"),
            "total_size": obj.get("total_size"),
            "parts": [UploadPartInfo.from_dict(_item) for _item in obj["parts"]] if obj.get("parts") is not None else None,
            "state": obj.get("state"),
            "expires_at": obj.get("expires_at")
        })
        return _obj


