//! Generated types from OpenAPI specification
//!
//! This file contains all the generated types for the API.
//! Do not edit manually - regenerate using the appropriate script.
//! Generated by openapi-to-rust v0.8.0. Source OpenAPI document: docs/openapi/openapi.yaml
#![allow(clippy::large_enum_variant)]
#![allow(clippy::format_in_format_args)]
#![allow(clippy::let_unit_value)]
#![allow(unreachable_patterns)]
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Page {
    pub items: Vec<PageItemsItem>,
    pub limit: i64,
    pub offset: i64,
    pub total: i64,
}
#[derive(Debug, Clone, Deserialize, Serialize, Default)]
pub struct PageItemsItem {}
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Operation {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ProblemDetails>,
    pub id: String,
    #[serde(rename = "resourceRef", skip_serializing_if = "Option::is_none")]
    pub resource_ref: Option<String>,
    pub state: OperationState,
}
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ProblemDetails {
    pub code: String,
    pub detail: String,
    pub status: i64,
    pub title: String,
    pub r#type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub violations: Option<Vec<ProblemDetailsViolationsItem>>,
}
#[derive(Debug, Clone, Deserialize, Serialize, Default)]
pub struct ProblemDetailsViolationsItem {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub field: Option<String>,
}
#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize, Default)]
pub enum OperationState {
    #[default]
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "cancelled")]
    Cancelled,
}
impl OperationState {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::Running => "running",
            Self::Succeeded => "succeeded",
            Self::Failed => "failed",
            Self::Cancelled => "cancelled",
        }
    }
}
impl ::std::fmt::Display for OperationState {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        f.write_str(self.as_str())
    }
}
impl AsRef<str> for OperationState {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct AddAssetRequest {
    pub digest: String,
    pub media_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    pub name: String,
    pub object_key: String,
    pub size: i64,
}
impl AddAssetRequest {
    /// Construct this request with every required wire field.
    pub fn new(
        digest: String,
        media_type: String,
        name: String,
        object_key: String,
        size: i64,
    ) -> Self {
        Self {
            digest,
            media_type,
            name,
            object_key,
            size,
            metadata: None,
        }
    }
    /// Start a dependency-free builder with every required wire field.
    pub fn builder(
        digest: String,
        media_type: String,
        name: String,
        object_key: String,
        size: i64,
    ) -> AddAssetRequestBuilder {
        AddAssetRequestBuilder::new(digest, media_type, name, object_key, size)
    }
}
/// Dependency-free builder for [`#struct_name`].
#[derive(Debug, Clone)]
#[must_use]
pub struct AddAssetRequestBuilder {
    value: AddAssetRequest,
}
impl AddAssetRequestBuilder {
    /// Start a builder with every required wire field.
    pub fn new(
        digest: String,
        media_type: String,
        name: String,
        object_key: String,
        size: i64,
    ) -> Self {
        Self {
            value: AddAssetRequest::new(digest, media_type, name, object_key, size),
        }
    }
    #[doc = concat!("Set the optional `", "metadata", "` request field.")]
    #[must_use]
    pub fn metadata(mut self, metadata: serde_json::Value) -> Self {
        self.value.metadata = Some(metadata);
        self
    }
    /// Finish building the request model.
    pub fn build(self) -> AddAssetRequest {
        self.value
    }
}
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct AnnotationProjectResponse {
    pub id: String,
    pub name: String,
    pub state: String,
}
#[derive(Debug, Clone, Deserialize, Serialize, Default)]
pub struct CompileRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub spec: Option<serde_json::Value>,
}
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct CompileResponse {
    pub capabilities: Vec<String>,
    pub digest: String,
    pub edge_count: i64,
    pub node_count: i64,
}
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct CreateAnnotationProjectRequest {
    pub dataset_version_id: String,
    pub name: String,
    pub project_id: String,
    pub task_type: String,
}
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct CreateDatasetRequest {
    pub name: String,
    pub project_id: String,
}
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct CreateDatasetVersionRequest {
    pub dataset_id: String,
}
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct CreateExperimentRequest {
    pub dataset_version_id: String,
    pub name: String,
    pub project_id: String,
    pub target_metric: String,
}
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct CreateModelRequest {
    pub name: String,
    pub project_id: String,
}
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct CreateTrainingJobRequest {
    pub argv: Vec<String>,
    pub code_digest: String,
    pub dataset_version_id: String,
    pub experiment_id: String,
    pub image_digest: String,
    pub project_id: String,
}
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct DatasetResponse {
    pub id: String,
    pub name: String,
    pub project_id: String,
    pub state: String,
    pub tenant_id: String,
}
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct DatasetVersionResponse {
    pub dataset_id: String,
    pub id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub manifest_digest: Option<String>,
    pub state: String,
}
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ExperimentResponse {
    pub id: String,
    pub name: String,
    pub state: String,
}
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GenerateSplitsRequest {
    pub seed: i64,
    pub test: f64,
    pub train: f64,
    pub val: f64,
}
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct HealthResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service: Option<String>,
    pub status: String,
}
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ModelResponse {
    pub id: String,
    pub name: String,
}
#[derive(Debug, Clone, Deserialize, Serialize, Default)]
pub struct OutboxEvent {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aggregate_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aggregate_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payload: Option<serde_json::Value>,
}
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ReadyResponse {
    pub ready: bool,
    pub status: String,
}
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct TrainingJobResponse {
    pub experiment_id: String,
    pub id: String,
    pub state: String,
}
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct WhoAmIResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub principal: Option<serde_json::Value>,
    pub request_id: String,
    pub tenant_id: String,
}
