# coding: utf-8

"""
    Moqentra API

    Northbound HTTP API for Moqentra.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moqentra_client.models.model_response import ModelResponse

class TestModelResponse(unittest.TestCase):
    """ModelResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelResponse:
        """Test ModelResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelResponse`
        """
        model = ModelResponse()
        if include_optional:
            return ModelResponse(
                id = '',
                name = ''
            )
        else:
            return ModelResponse(
                id = '',
                name = '',
        )
        """

    def testModelResponse(self):
        """Test ModelResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
