# coding: utf-8

"""
    Moqentra API

    Northbound HTTP API for Moqentra.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moqentra_client.models.create_upload_session_request import CreateUploadSessionRequest

class TestCreateUploadSessionRequest(unittest.TestCase):
    """CreateUploadSessionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateUploadSessionRequest:
        """Test CreateUploadSessionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateUploadSessionRequest`
        """
        model = CreateUploadSessionRequest()
        if include_optional:
            return CreateUploadSessionRequest(
                resource_type = '',
                resource_id = '',
                version_id = '',
                name = '',
                media_type = '',
                part_size = 56,
                total_size = 56,
                ttl_seconds = 56
            )
        else:
            return CreateUploadSessionRequest(
                resource_type = '',
                resource_id = '',
                version_id = '',
                name = '',
                media_type = '',
                part_size = 56,
                total_size = 56,
        )
        """

    def testCreateUploadSessionRequest(self):
        """Test CreateUploadSessionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
