# coding: utf-8

"""
    Moqentra API

    Northbound HTTP API for Moqentra.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moqentra_client.models.label_u_project_config import LabelUProjectConfig

class TestLabelUProjectConfig(unittest.TestCase):
    """LabelUProjectConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LabelUProjectConfig:
        """Test LabelUProjectConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LabelUProjectConfig`
        """
        model = LabelUProjectConfig()
        if include_optional:
            return LabelUProjectConfig(
                version = '',
                media_type = '',
                tools = [
                    moqentra_client.models.label_u_tool_config.LabelUToolConfig(
                        tool = '', 
                        config = moqentra_client.models.config.config(), )
                    ]
            )
        else:
            return LabelUProjectConfig(
                version = '',
                media_type = '',
                tools = [
                    moqentra_client.models.label_u_tool_config.LabelUToolConfig(
                        tool = '', 
                        config = moqentra_client.models.config.config(), )
                    ],
        )
        """

    def testLabelUProjectConfig(self):
        """Test LabelUProjectConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
