# coding: utf-8

"""
    Moqentra API

    Northbound HTTP API for Moqentra.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moqentra_client.models.upload_part_info import UploadPartInfo

class TestUploadPartInfo(unittest.TestCase):
    """UploadPartInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UploadPartInfo:
        """Test UploadPartInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UploadPartInfo`
        """
        model = UploadPartInfo()
        if include_optional:
            return UploadPartInfo(
                part_number = 56,
                size = 56,
                completed = True
            )
        else:
            return UploadPartInfo(
                part_number = 56,
                size = 56,
                completed = True,
        )
        """

    def testUploadPartInfo(self):
        """Test UploadPartInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
