# coding: utf-8

"""
    Moqentra API

    Northbound HTTP API for Moqentra.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moqentra_client.models.annotation_response import AnnotationResponse

class TestAnnotationResponse(unittest.TestCase):
    """AnnotationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnnotationResponse:
        """Test AnnotationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnnotationResponse`
        """
        model = AnnotationResponse()
        if include_optional:
            return AnnotationResponse(
                id = '',
                task_id = '',
                asset_id = '',
                revision = 56,
                client_update_id = '',
                actor_id = '',
                payload = None
            )
        else:
            return AnnotationResponse(
                id = '',
                task_id = '',
                asset_id = '',
                revision = 56,
                client_update_id = '',
                actor_id = '',
                payload = None,
        )
        """

    def testAnnotationResponse(self):
        """Test AnnotationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
