# coding: utf-8

"""
    Moqentra API

    Northbound HTTP API for Moqentra.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moqentra_client.models.create_import_job_request import CreateImportJobRequest

class TestCreateImportJobRequest(unittest.TestCase):
    """CreateImportJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateImportJobRequest:
        """Test CreateImportJobRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateImportJobRequest`
        """
        model = CreateImportJobRequest()
        if include_optional:
            return CreateImportJobRequest(
                source_url = '',
                target_key = '',
                media_type = '',
                total_bytes = 56,
                concurrency = 56,
                deadline_seconds = 56
            )
        else:
            return CreateImportJobRequest(
                source_url = '',
                target_key = '',
                media_type = '',
                total_bytes = 56,
        )
        """

    def testCreateImportJobRequest(self):
        """Test CreateImportJobRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
