# coding: utf-8

"""
    Moqentra API

    Northbound HTTP API for Moqentra.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moqentra_client.models.generate_splits_request import GenerateSplitsRequest

class TestGenerateSplitsRequest(unittest.TestCase):
    """GenerateSplitsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenerateSplitsRequest:
        """Test GenerateSplitsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenerateSplitsRequest`
        """
        model = GenerateSplitsRequest()
        if include_optional:
            return GenerateSplitsRequest(
                seed = 56,
                train = 1.337,
                val = 1.337,
                test = 1.337
            )
        else:
            return GenerateSplitsRequest(
                seed = 56,
                train = 1.337,
                val = 1.337,
                test = 1.337,
        )
        """

    def testGenerateSplitsRequest(self):
        """Test GenerateSplitsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
