# coding: utf-8

"""
    Moqentra API

    Northbound HTTP API for Moqentra.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moqentra_client.models.import_job_response import ImportJobResponse

class TestImportJobResponse(unittest.TestCase):
    """ImportJobResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportJobResponse:
        """Test ImportJobResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportJobResponse`
        """
        model = ImportJobResponse()
        if include_optional:
            return ImportJobResponse(
                id = '',
                state = '',
                source_url = '',
                target_key = '',
                media_type = '',
                total_bytes = 56,
                transferred_bytes = 56,
                concurrency = 56,
                deadline_seconds = 56,
                digest = '',
                failure = '',
                retry_count = 56
            )
        else:
            return ImportJobResponse(
                id = '',
                state = '',
                source_url = '',
                target_key = '',
                media_type = '',
                total_bytes = 56,
                transferred_bytes = 56,
                concurrency = 56,
                deadline_seconds = 56,
                retry_count = 56,
        )
        """

    def testImportJobResponse(self):
        """Test ImportJobResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
