# coding: utf-8

"""
    Moqentra API

    Northbound HTTP API for Moqentra.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moqentra_client.models.create_tasks_request import CreateTasksRequest

class TestCreateTasksRequest(unittest.TestCase):
    """CreateTasksRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateTasksRequest:
        """Test CreateTasksRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateTasksRequest`
        """
        model = CreateTasksRequest()
        if include_optional:
            return CreateTasksRequest(
                asset_ids = [
                    ''
                    ]
            )
        else:
            return CreateTasksRequest(
                asset_ids = [
                    ''
                    ],
        )
        """

    def testCreateTasksRequest(self):
        """Test CreateTasksRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
