# coding: utf-8

"""
    Moqentra API

    Northbound HTTP API for Moqentra.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moqentra_client.models.who_am_i_response import WhoAmIResponse

class TestWhoAmIResponse(unittest.TestCase):
    """WhoAmIResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WhoAmIResponse:
        """Test WhoAmIResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WhoAmIResponse`
        """
        model = WhoAmIResponse()
        if include_optional:
            return WhoAmIResponse(
                principal = None,
                tenant_id = '',
                request_id = ''
            )
        else:
            return WhoAmIResponse(
                tenant_id = '',
                request_id = '',
        )
        """

    def testWhoAmIResponse(self):
        """Test WhoAmIResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
