# coding: utf-8

"""
    Moqentra API

    Northbound HTTP API for Moqentra.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moqentra_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_abort_upload_session(self) -> None:
        """Test case for abort_upload_session

        Abort an upload session
        """
        pass

    def test_activate_annotation_project(self) -> None:
        """Test case for activate_annotation_project

        Activate annotation project
        """
        pass

    def test_add_dataset_version_asset(self) -> None:
        """Test case for add_dataset_version_asset

        Add an asset to a draft dataset version
        """
        pass

    def test_admit_training_job(self) -> None:
        """Test case for admit_training_job

        Admit a training job
        """
        pass

    def test_cancel_training_job(self) -> None:
        """Test case for cancel_training_job

        Cancel a training job
        """
        pass

    def test_compile_application(self) -> None:
        """Test case for compile_application

        Compile an application graph
        """
        pass

    def test_complete_upload_session(self) -> None:
        """Test case for complete_upload_session

        Complete an upload session
        """
        pass

    def test_create_annotation_project(self) -> None:
        """Test case for create_annotation_project

        Create annotation project
        """
        pass

    def test_create_dataset(self) -> None:
        """Test case for create_dataset

        Create dataset
        """
        pass

    def test_create_dataset_version(self) -> None:
        """Test case for create_dataset_version

        Create dataset version
        """
        pass

    def test_create_experiment(self) -> None:
        """Test case for create_experiment

        Create experiment
        """
        pass

    def test_create_model(self) -> None:
        """Test case for create_model

        Create model family
        """
        pass

    def test_create_training_job(self) -> None:
        """Test case for create_training_job

        Create training job
        """
        pass

    def test_create_upload_session(self) -> None:
        """Test case for create_upload_session

        Create a multipart upload session
        """
        pass

    def test_generate_dataset_version_splits(self) -> None:
        """Test case for generate_dataset_version_splits

        Generate deterministic train/val/test splits
        """
        pass

    def test_get_dataset(self) -> None:
        """Test case for get_dataset

        Get dataset by id
        """
        pass

    def test_get_health(self) -> None:
        """Test case for get_health

        Liveness probe
        """
        pass

    def test_get_ready(self) -> None:
        """Test case for get_ready

        Readiness probe
        """
        pass

    def test_get_upload_session(self) -> None:
        """Test case for get_upload_session

        Get upload session
        """
        pass

    def test_list_datasets(self) -> None:
        """Test case for list_datasets

        List datasets for tenant
        """
        pass

    def test_list_experiments(self) -> None:
        """Test case for list_experiments

        List experiments
        """
        pass

    def test_list_models(self) -> None:
        """Test case for list_models

        List models
        """
        pass

    def test_list_outbox_events(self) -> None:
        """Test case for list_outbox_events

        List outbox events
        """
        pass

    def test_list_part_upload_urls(self) -> None:
        """Test case for list_part_upload_urls

        List signed URLs for uploading parts
        """
        pass

    def test_list_training_jobs(self) -> None:
        """Test case for list_training_jobs

        List training jobs
        """
        pass

    def test_list_upload_session_parts(self) -> None:
        """Test case for list_upload_session_parts

        List upload session parts
        """
        pass

    def test_publish_dataset_version(self) -> None:
        """Test case for publish_dataset_version

        Publish a dataset version
        """
        pass

    def test_upload_part(self) -> None:
        """Test case for upload_part

        Upload a part
        """
        pass

    def test_who_am_i(self) -> None:
        """Test case for who_am_i

        Resolve authenticated principal
        """
        pass


if __name__ == '__main__':
    unittest.main()
