# coding: utf-8

"""
    Moqentra API

    Northbound HTTP API for Moqentra.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moqentra_client.models.outbox_event import OutboxEvent

class TestOutboxEvent(unittest.TestCase):
    """OutboxEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutboxEvent:
        """Test OutboxEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutboxEvent`
        """
        model = OutboxEvent()
        if include_optional:
            return OutboxEvent(
                id = '',
                aggregate_type = '',
                aggregate_id = '',
                event_type = '',
                payload = None
            )
        else:
            return OutboxEvent(
        )
        """

    def testOutboxEvent(self):
        """Test OutboxEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
