# coding: utf-8

"""
    Moqentra API

    Northbound HTTP API for Moqentra.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moqentra_client.models.compile_response import CompileResponse

class TestCompileResponse(unittest.TestCase):
    """CompileResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompileResponse:
        """Test CompileResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompileResponse`
        """
        model = CompileResponse()
        if include_optional:
            return CompileResponse(
                digest = '',
                edge_count = 56,
                node_count = 56,
                capabilities = [
                    ''
                    ]
            )
        else:
            return CompileResponse(
                digest = '',
                edge_count = 56,
                node_count = 56,
                capabilities = [
                    ''
                    ],
        )
        """

    def testCompileResponse(self):
        """Test CompileResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
