apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "moqentra.fullname" . }}-control-plane
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: moqentra
    app.kubernetes.io/component: control-plane
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "moqentra.fullname" . }}-node-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: moqentra
    app.kubernetes.io/component: node-agent
automountServiceAccountToken: true
