issuer: http://localhost:5556/dex
storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db
web:
  http: 0.0.0.0:5556
oauth2:
  skipApprovalScreen: true
staticClients:
  - id: moqentra-console
    redirectURIs:
      - http://localhost:3000/callback
    name: Moqentra Console
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0
enablePasswordDB: true
staticPasswords:
  - email: admin@example.com
    hash: JDJhJDEwJEVDTjhiam5kVVByQVN1V0VrWmUvdGVXSmFLdHdxRy5qS1NTbkxhQktxQ0JNd2d2d09QMWJX
    username: admin
    userID: 08a8684b-db88-4b73-90a9-3cd1661f5446
